### ISSUE TITLE
Add enum toString generation

### ISSUE THREAD

**Issue by kevinsdooapp** [highsource/jaxb2-basics#31]
Could be nice to override the toString method of enum to use a resource bundle for example.

You'll find a [pull request [here]](https://github.com/highsource/jaxb2-basics/pull/32) that add this behaviour as an option "-XenumToString"

**Comment by highsource** [comment]
Hi @kevinsdooapp,

sorry for the late reply.

I've reviewed your suggestion, thought it over and came to the conclusion that this can be already covered by the existing infrastructure. I don't think there is a need for another plugin.

The goal is to be able to customize, how enum is turned to string, this can already be done in the strategy. For instance, consider we want to print out value of the enum instead of its name. Here's our enum:

```java
@XmlType(name = "issueGH31Type")
@XmlEnum
public enum IssueGH31Type
    implements EnumValue<String>
{

    @XmlEnumValue("Male")
    MALE("Male"),
    @XmlEnumValue("Female")
    FEMALE("Female");
    private final String value;

    IssueGH31Type(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IssueGH31Type fromValue(String v) {
        for (IssueGH31Type c: IssueGH31Type.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public String enumValue() {
        return this.value();
    }

}
```

In the strategy we can just implement the `append` method to check if the value is instance of `EnumValue` and use the value of the enum to convert it to string:

```java
final ToStringStrategy2 s = new JAXBToStringStrategy() {
			// ...

			public StringBuilder append(ObjectLocator locator,
					StringBuilder buffer, Object value) {

				if (value instanceof EnumValue<?>) {
					return super.append(locator, buffer,
							((EnumValue<?>) value).enumValue());
				} else {
					return super.append(locator, buffer, value);
				}
			};
		};
```

This produces `Male`/`Female` instead of `MALE`/`FEMALE` for `IssueGH31Type`.
You can argue whether `instanceof` is good or not, but that'd be better solved with the visitor pattern, making enums implement `ToString` won't help much with that.

Enums don't need to implement the `ToString` interface because they are atomic values. And it's the responsibility of the strategy to decide how individual values should be converted to strings.

So I don't see any necessity for enums to implement `ToString`.

Accordingly I'm intending to close this issue and the pull request #32 as `wontfix`. I'd be grateful to know what you think, if maybe I'm missing something.

And thank you for your effort. I am sorry it took me so long to et to this issue.

Best wishes,
Alexey
