### ISSUE TITLE
Boolean getters plugin

### ISSUE THREAD

**Issue by highsource** [highsource/jaxb2-basics#65]
http://jira.highsource.org/browse/JIIB-21

**Comment by AndreasIgelCC** [comment]
Is that plugin meant for fixing the common problem of `public Boolean is` Getters in JAXB-Gneration?

**Comment by AndreasIgelCC** [comment]
> Is that plugin meant for fixing the common problem of `public Boolean is` Getters in JAXB-Gneration?

Hi @mattrpav, you may have access to that jira-description. Does that close the failure of generated Getters of Booleans starting with is?

**Comment by laurentschoelens** [comment]
Hi @AndreasIgelCC
The jira is sadly offline so we lose all data in it.
My guess was this issue was related to taking the XJC plugins in `org.andromda.thirdparty.jaxb2_commons` inside jaxb2-basics.

One of the plugin was *BooleanGetter plugin* : which generate getXXX instead of isXXX method for boolean

Wiki documentation of [that plugin is here](https://github.com/highsource/jaxb-tools/wiki/JAXB-Boolean-Getter-Plugin)

This plugin is available in v4.x of jaxb-tools, starting with [4.0.2](https://github.com/highsource/jaxb-tools/releases/tag/4.0.2)

Do you need them in jaxb2-basics for jaxb2 ?

**Comment by AndreasIgelCC** [comment]
Currently we fix that with a search/replace script after generation of Java-Files. The generation of "public Boolean isField()" is an error, because default XML-Parsers get problems afterwards with that. So if you are able to fix that in jaxb2-basics too, that would be great!

**Comment by laurentschoelens** [comment]
For jaxb 2.x, you could use the following :
```xml
<dependency>
    <groupId>org.andromda.thirdparty.jaxb2_commons</groupId>
    <artifactId>booleangetter</artifactId>
    <version>1.0</version>
</dependency>
```

For jaxb 4, you can use the `org.jvnet.jaxb:jaxb-plugins` from jaxb-tools.
Tell me if you need more info about it

**Comment by AndreasIgelCC** [comment]
Thank you for the response and the hints. I will take that into project team and having a check on it.

**Comment by laurentschoelens** [comment]
Feel free to comment again when your investigations are done 😄

**Comment by laurentschoelens** [comment]
https://github.com/highsource/jaxb-tools/issues/460 will be backported in jaxb-tools v2 so will be available too with up-to-date versions when v2.x will be released

**Comment by AndreasIgelCC** [comment]
Thank you @laurentschoelens  for the hints. We changed it now when updating to jaxb4. Unfortunately this is not a solution. By using the boolean-getters plugin, all getters with boolean/Boolean gets a get instead a is. We solved it at the end by adding to configuration:
```xml
<enableIntrospection>true</enableIntrospection>
``` 
Maybe it would be a good idea, to document it in https://github.com/highsource/jaxb-tools/wiki/JAXB-Boolean-Getter-Plugin?
